# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22869f03c45daed72165c3bcf5d9774887f3b2ab9d3f493b0df296867caed72f233ce36646e32a2f7604b080a19fefc04adc1d80441b0ab9a57ca10db2ea77dd

test:
  secret_key_base: 1e1b7d12f9f33da1d031ebce56a2d0210cf1f319f8bc6e1406cb6fe5cda2aa4708f80365dfe94acec160ab305c7b505d13d2089e9a677fb7bf51af29ba5dd2f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
